version: '3'
services:
  nginx:
      build: ./nginx
      container_name: nginx
      networks:
        - cote
      links:
        - broker1:broker1
        - broker2:broker2
        - broker3:broker3
        - broker4:broker4
      ports:
        - "1883:8883"
  broker1:
    build: .
    container_name: broker1
    networks:
      - cote
      - redis
    environment:
      - WS_SERVER_URL=ws://playground.dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false
  broker2:
    build: .
    container_name: broker2
    networks:
      - cote
      - redis
    environment:
      - WS_SERVER_URL=ws://playground.dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false
  broker3:
    build: .
    container_name: broker3
    networks:
      - cote
      - redis
    environment:
      - WS_SERVER_URL=ws://playground.dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false
  broker4:
    build: .
    container_name: broker4
    networks:
      - cote
      - redis
    environment:
      - WS_SERVER_URL=ws://playground.dev.devicehive.com/api/websocket
      - REDIS_SERVER_HOST=redis
      - REDIS_SERVER_PORT=6379
      - ENABLE_PM=false
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - redis
networks:
  redis:
    driver: bridge
  cote:
    driver: bridge